### ISSUE TITLE
Implement this!

### ISSUE THREAD

**Issue by workmanw** [workmanw/ember-did-change-attrs#1]
Originally started: https://github.com/workmanw/ember-diff-attrs/issues/4 .

Rough out of the API provided by @GavinJoyce :

```javascript
import DidChangeAttrs from 'ember-did-change-attrs';

export default Ember.Component.extend(DidChangeAttrs, {
  didChangeAttrsConfig: {
    attrs: ['email', 'isAdmin']
  },
 
  didChangeAttrs(changes) {
    if(changes.email) {
      let oldEmail = changes.email.previous,
          newEmail = changes.email.current;
      // Do stuff
    }
  }
});
```

**Comment by workmanw** [comment]
The biggest concern I had about this API when I looked at it was regarding inheritance. What would happen if someone wanted to extend a component that was using `DidChangeAttrs` and use it themself? Specifically around the `didChangeAttrsConfig`. 

We could:

1. Say sorry, it's not supported
2. Make it a `concatenatedProperties` and/or `mergedProperties`
3. ???

**Comment by GavinJoyce** [comment]
If it's going to be a hash, `mergedProperties` seems like a fine solution
