### ISSUE TITLE
Remove "WIP" label // production-ready

### ISSUE THREAD

**Issue by erichaus** [workmanw/ember-did-change-attrs#18]
Hello, I've previously used diff-attrs and like the idea behind it, then discovered this newer version which I like even more because it's easily unit-testable.

However there is the "WIP" label and I'm wondering if there is enough confidence to remove that so teams can know this is production-ready? It seems to be working in our app but we're hesitant to use something that says "WIP".

Thanks!

**Comment by waissbluth** [comment]
same here, has anyone had any issues with it? @erichonkanen have you been using it in production?

**Comment by GavinJoyce** [comment]
We've been using this at Intercom for over a year in production without issue
